# .github/workflows/version-bump.yml
name: Version Bump

on:
  push:
    branches: [main]
    paths-ignore:
      - "package.json"
      - "package-lock.json"

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump Version
        run: |
          npm version patch -no-git-tag-version

      - name: Commit and Push
        run: |
          git add package.json
          git commit -m "ci: bump version [skip ci]"
          git push
