name: Version Bump

# Triggers workflow on push to main branch
on:
  push:
    branches: [main]
    paths-ignore:
      # Prevents infinite loop by ignoring version file changes
      - "package.json"
      - "package-lock.json"

# Grants write permission for pushing changes
permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Configure Git identity for commits
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # Version bump logic based on commit messages
      - name: Determine Version Bump
        run: |
          if git log -1 --pretty=%B | grep -i "BREAKING CHANGE"; then
            npm version major -no-git-tag-version
          elif git log -1 --pretty=%B | grep -i "feat"; then
            npm version minor -no-git-tag-version
          else
            npm version patch -no-git-tag-version
          fi

      # Commit and push version changes
      - name: Commit and Push
        run: |
          git add package.json
          git commit -m "ci: bump version [skip ci]"
          git push
